name: CHIL 2024
tagline: Conference on <br> Health, Inference, and Learning
date: June 2024 <br> <small>New York City, NY, United States</small>
countdown_date: June, 2024
citation_date: June 2024
proceedings_title: Proceedings of CHIL 2024
analytics: UA-
logo:
  image:
  width: auto
  height: 50px
  alt_text: 'CHIL logo'
# uncomment the following line to show the site title next to the logo image
site_title: CHIL 2024
page_title:
  prefix: 'CHIL'
  separator: ': '
background_image: /static/images/main.jpg
organization: CHIL Organization Committee
registration:
  url: 'register.html'
  link_text: Registration opens February 2023

# Remove or change to your chat server.
chat_server: chat.chilconference.org
default_chat_channel: general
# Live stream presentation ID
default_presentation_id: 38954751
default_poster_pdf: /static/images/GLTR_poster.pdf


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0: true
auth0_client_id : idrCis50v8uMru0k189CZY3LXVK9tUnY
auth0_domain : chil.us.auth0.com
auth0_authorize_endpoint: https://chil.us.auth0.com/authorize

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday
