name: MiniConf
tagline: MINICONF <br> CONFERENCE <br> MANAGEMENT
data: May 2020
analytics: UA-
logo:
  image: static/images/MiniConf.png
  width: 180px
# uncomment the following line if show the site title next to the logo image
# site_title: MiniConf
background_image: static/images/main.jpg
organization: MiniConf Organization Committee
calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday

