name: ACM-CHIL 2020
tagline: ACM Conference on <br> Health, Inference, and Learning
date: July 23/24th 2020
citation_date: July 2020
proceedings_title: Proceedings of ACM-CHIL 2020
analytics: UA-
logo:
  image: static/images/acm_92x192.png
  width: 50px
  height: auto
# uncomment the following line to show the site title next to the logo image
site_title: ACM-CHIL 2020
page_title:
  prefix: 'ACM-CHIL'
  separator: ': '
background_image: static/images/main.jpg
organization: ACM-CHIL Organization Committee
registration: 'http://www.cvent.com/events/acm-conference-on-health-inference-and-learning-chil-2020-/event-summary-c40cab906b3c48cfa2be7dfb100fc753.aspx'

# Remove or change to your chat server.
chat_server: chat.chilconference.org
default_presentation_id: 38922815
default_poster_pdf: static/images/GLTR_poster.pdf


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'

  sunday_saturday: false  #  Include Sunday and Saturday
  
